### ISSUE TITLE
_id is undefined, console error

### ISSUE THREAD

**Issue by kevinfengcs88** [kevinfengcs88/wavedash#84]
```
ChatLogics.js:2 Uncaught TypeError: Cannot read properties of undefined (reading '_id')
    at getSender (ChatLogics.js:2:1)
    at MyChats.js:99:1
    at Array.map (<anonymous>)
    at MyChats (MyChats.js:87:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
```

**Comment by Vitaliy-Steffensen** [comment]
Hi, it is hard to debug without the code. But it could be caused by the javascript var error, where you can refference a var variable before its declared in the code. Then you will recieve undefined, whereas const and let would throw an error. If it's not becasue you are using a var before its declared it could because you are trying to map an array which value is not defined yet. So if you have a usestate() or a usestate(null), where you instead should give ot the initial value of an empty array, like so usestate([ ]) .

But if none of the above, you could try sharing your code, so how you manipulate the variable.
